name: Unit Test

on: [push]

jobs:
  test-led-scheduler:
    runs-on: ubuntu-latest
    name: Build and run ex-led-scheduler unit tests Docker image
    # if: github.ref != 'refs/heads/chp10'
    steps:
        # Check out from this repo
      - name: Check out this repo
        uses: actions/checkout@v3

        # Build the docker image
      - name: Build Docker image
        run: docker build -t ex-led-scheduler-image:v1 -f ./ex-led-scheduler/Dockerfile ./ex-led-scheduler

        # Run the image
      - name: Run image
        run: docker run --rm ex-led-scheduler-image:v1

        # Delete the docker image
      - name: Remove docker image
        run: docker rmi ex-led-scheduler-image:v1
  
  test-alarm-clock-service:
    runs-on: ubuntu-latest
    name: Build and run ex-alarm-clock-service unit tests Docker image
    # if: github.ref != 'refs/heads/chp10'
    steps:
        # Check out from this repo
      - name: Check out this repo
        uses: actions/checkout@v3

        # Build the docker image
      - name: Build Docker image
        run: docker build -t ex-acs-image:v1 -f ./ex-alarm-clock-service/Dockerfile ./ex-alarm-clock-service

        # Run the image
      - name: Run image
        run: docker run --rm ex-acs-image:v1

        # Delete the docker image
      - name: Remove docker image
        run: docker rmi ex-acs-image:v1

  test-circular-buffer-chp9:
    runs-on: ubuntu-latest
    name: Build and run ex-circular-buffer-chp9 unit tests Docker image
    # if: github.ref != 'refs/heads/chp10'
    steps:
        # Check out from this repo
      - name: Check out this repo
        uses: actions/checkout@v3

        # Build the docker image
      - name: Build Docker image
        run: docker build -t ex-cb-chp9-image:v1 -f ./ex-circular-buffer-chp9/Dockerfile ./ex-circular-buffer-chp9

        # Run the image
      - name: Run image
        run: docker run --rm ex-cb-chp9-image:v1

        # Delete the docker image
      - name: Remove docker image
        run: docker rmi ex-cb-chp9-image:v1

  # test-mockio-cfi:
  #   runs-on: ubuntu-latest
  #   name: Build and run ex-mockio-cfi unit tests Docker image
  #   # if: github.ref != 'refs/heads/chp10'
  #   steps:
  #       # Check out from this repo
  #     - name: Check out this repo
  #       uses: actions/checkout@v3

  #       # Build the docker image
  #     - name: Build Docker image
  #       run: docker build -t ex-mockio-cfi-image:v1 -f ./ex-mockio-cfi/Dockerfile ./ex-mockio-cfi

  #       # Run the image
  #     - name: Run image
  #       run: docker run --rm ex-mockio-cfi-image:v1

  #       # Delete the docker image
  #     - name: Remove docker image
  #       run: docker rmi ex-mockio-cfi-image:v1

  test-erase-suspend:
    runs-on: ubuntu-latest
    name: Build and run ex-erase-suspend-resume-flowchart unit tests Docker image
    # if: github.ref == 'refs/heads/chp10'
    steps:
        # Check out from this repo
      - name: Check out this repo
        uses: actions/checkout@v3

        # Build the docker image
      - name: Build Docker image
        run: docker build -t ex-erase-suspend-image:v1 -f ./ex-erase-suspend-resume-flowchart/Dockerfile ./ex-erase-suspend-resume-flowchart

        # Run the image
      - name: Run image
        run: docker run --rm ex-erase-suspend-image:v1

        # Delete the docker image
      - name: Remove docker image
        run: docker rmi ex-erase-suspend-image:v1