name: Unit Test

on: [push]

jobs:
  test-led-scheduler:
    runs-on: ubuntu-latest
    name: Build and run ex-led-scheduler unit tests Docker image
    steps:
        # Check out from this repo
      - name: Check out this repo
        uses: actions/checkout@v3

        # Build the docker image
      - name: Build Docker image
        run: docker build -t ex-led-scheduler-image:v1 -f ./ex-led-scheduler/Dockerfile ./ex-led-scheduler

        # Run the image
      - name: Run image
        run: docker run --rm ex-led-scheduler-image:v1

        # Delete the docker image
      - name: Remove docker image
        run: docker rmi ex-led-scheduler-image:v1
  
  test-alarm-clock-service:
    runs-on: ubuntu-latest
    name: Build and run ex-alarm-clock-service unit tests Docker image
    steps:
        # Check out from this repo
      - name: Check out this repo
        uses: actions/checkout@v3

        # Build the docker image
      - name: Build Docker image
        run: docker build -t ex-acs-image:v1 -f ./ex-alarm-clock-service/Dockerfile ./ex-alarm-clock-service

        # Run the image
      - name: Run image
        run: docker run --rm ex-acs-image:v1

        # Delete the docker image
      - name: Remove docker image
        run: docker rmi ex-acs-image:v1