name: Unit Test

on: [push]

jobs:
  doocker-unit-tests:
    runs-on: ubuntu-latest
    name: Build and run ex-led-scheduler unit tests Docker image
    steps:
        # Check out from this repo
      - name: Check out this repo
        uses: actions/checkout@v3

        # Build the docker image
      - name: Build Docker image
        run: docker build -t ex-led-scheduler-image:v1 -f ./ex-led-scheduler/Dockerfile ./ex-led-scheduler

        # Run the image
      - name: Run image
        run: docker run --rm ex-led-scheduler-image:v1

        # Delete the docker image
      - name: Remove docker image
        run: docker rmi ex-led-scheduler-image:v1